language: php
env:
  global:
    - secure: I/8TWUxe4NJp47f4pKhndulMqKiz4kM562eSPGYFrKWnvTlKgu/4O8pHsVRhtTyhrUdYaK9A0FhqecaxaA9ASiG3ATQ3wgJMJcjve2BzAA1eCO9n64/u5y9vuNJWPQ/LApaH5AZZPTcrDPRwtPWCPpOfB66Gek0xX67Bsu8vOEKuDOXzPqll/km7FJqGdLlR2J7jP1J8JnAq36uN54Gc7NecZjLiRwPEVvFoWW7mlQxmyOcj6Qu92nY+pODhy9CvS+XL1XB80nMggAZSARhOgPv7C9gjw/HGUZ8AZqZ85DkBXW5Watbk3XDEyVkMse73asihnoXz5rAELEoSDlWTtONaZLLi2tpWJdJzVLxTVVM2wp9E8uZnCD7w3MfZWeYy6E06hKfBkN2U7w0DKho48OL4u/QDLh1rOa67qfejwoPRNgInIb4eK0i/x5+Gg7r22s0iU+qRGGlkZNHjLbg2yEbcJZ7g0Wiu91fhPZNbirvx+YOFekfXQit0CdKo/kTqR0PDtG0StowDi1359to+Zkn24EE2l+Xiw1IPKNX6ag2ph2hLN6+4JIHghLPNoarfFJtCVXLrOobpIxMN/hLY1FZ9we27beJ/mTTClJAAG9jCXzERMOcHOWCjdd44kas5VaAeyEfu9Mm3ZXu5e0H5bFzaNRRnqb3qDGgY7pjuLDM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: builds@travis-ci.org
    - TRAVIS_REPO_SLUG: jarscr/teo
    - GIT_BRANCH: master
matrix:
  fast_finish: true
sudo: required
dist: trusty
php:
- '7.3'
addons:
  hosts:
    - local.dev
cache:
  - apt
before_script:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes apache2
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt update
  - sudo apt-get install -y --force-yes php7.3 php7.3-common php7.3-mysql php7.3-xml php7.3-xmlrpc php7.3-curl php7.3-gd php7.3-imagick php7.3-cli php7.3-dev php7.3-imap php7.3-mbstring php7.3-opcache php7.3-soap php7.3-zip php7.3-intl
  - sudo cp travisCI/defaultsite.tpl /etc/apache2/sites-available/000-default.conf
  - sudo cp -R App /var/www/html/App
  - sudo cp -R Core /var/www/html/Core
  - sudo cp -R public /var/www/html/public
  - sudo cp .htaccess /var/www/html/.htaccess
  - sudo a2enmod rewrite
  - sudo cp travisCI/servername.tpl /etc/apache2/conf-available/servername.conf
  - sudo a2enconf servername
  - sudo service apache2 restart
  - sudo service php7.3-fpm restart
install:
  - composer install
script: 
 # Do a lookup on local.dev hostname set above 
  - nslookup local.dev
  # Do an Apache Config Test
  - sudo apache2ctl configtest
  # Check Apache Version
  - sudo apache2 -v
  # Check PHP Version
  - sudo php -v
  # Check if the site responds OK
  - curl -vsf 'http://local.dev:80/' &> /dev/stdout
  # Test if PHP is working
  - curl -vsf 'http://local.dev:80/' &> /dev/stdout
  # Test a Good User-Agent String against our site (later we test bad bots here)
  - curl -A "googlebot" http://local.dev:80/ &> /dev/stdout
  # Test Some Bad Bots and Referrers
  - STATUSCODE=$(curl -A "80legs" http://local.dev:80/ &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 403; then exit 0; fi
  - STATUSCODE=$(curl -A "masscan" http://local.dev:80/ &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 403; then exit 0; fi
  - STATUSCODE=$(curl -I http://local.dev:80/ -e http://100dollars-seo.com &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 403; then exit 0; fi
  - STATUSCODE=$(curl -I http://local.dev:80/ -e http://zx6.ru &> /dev/stderr --write-out "%{http_code}") | if test $STATUSCODE 403; then exit 0; fi
  - cat /tmp/error.log
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file:
  - "README.md"
  skip_cleanup: true
  on:
    repo: jarscr/teo
    tags: false
    all_branches: true
notifications:
    email: false
services:
  - mysql
before_install:
  - mysql -u root --password="" < teo.sql